version: "3"
services:
  redis-server:
    image: 'redis'
    networks:
        - webnet
  web:
    image: tomek371240/session:4
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
        - "8081:8080"
    networks:
        - webnet
networks:
  webnet:

#  docker stack deploy -c docker-compose.yml tomek_session_stack